USE master
GO

IF EXISTS (SELECT * FROM sys.databases WHERE name = 'CourseSutudent')
DROP DATABASE CourseSutudent
GO

CREATE DATABASE CourseSutudent
GO

USE CourseSutudent
GO

CREATE TABLE STUDENT(
	SSN INT NOT NULL PRIMARY KEY,
	Name nvarchar(20) NOT NULL,
	Major nvarchar(20) NOT NULL,
	Bdate datetime NOT NULL
	)
GO

CREATE TABLE COURSE(
	Course int NOT NULL PRIMARY KEY,
	Cname nvarchar(20) NOT NULL,
	Dept nvarchar(50) NOT NULL
	)
GO

CREATE TABLE ENROLL(
	SSN int NOT NULL,
	Course int NOT NULL,
	PRIMARY KEY(SSN,Course),
	Quarter int NOT NULL,
	Grade int NOT NULL
	CONSTRAINT FK_ENROLL_STUDENT FOREIGN KEY(SSN) REFERENCES STUDENT(SSN),
	CONSTRAINT FK_ENROLL_COURSE FOREIGN KEY(Course) REFERENCES COURSE(Course),
	)
GO
CREATE TABLE TEXT(
	Book_ISBN int NOT NULL PRIMARY KEY,
	Book_title nvarchar(20) NOT NULL,
	Publisher nvarchar(20) NOT NULL,
	Author nvarchar(20) NOT NULL
	)
GO
CREATE TABLE BOOK_ADOPTION(
	Course int NOT NULL,
	Book_ISBN int NOT NULL,
	Quarter int NOT NULL,
	PRIMARY KEY(Course,Book_ISBN),
	CONSTRAINT FK_BOOK_ADOPTION_COURSE FOREIGN KEY(Course) REFERENCES COURSE(Course),
	CONSTRAINT FK_BOOK_ADOPTION_TEXT FOREIGN KEY(Book_ISBN) REFERENCES TEXT(Book_ISBN)
	)
GO
